// <auto-generated />
using System;
using InterLoad.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InterLoad.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CollectActionCollectDemand", b =>
                {
                    b.Property<int>("CollectActionsId")
                        .HasColumnType("integer");

                    b.Property<int>("CollectDemandsId")
                        .HasColumnType("integer");

                    b.HasKey("CollectActionsId", "CollectDemandsId");

                    b.HasIndex("CollectDemandsId");

                    b.ToTable("CollectActionCollectDemand");
                });

            modelBuilder.Entity("InterLoad.Models.Ef.CollectAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Collected")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KeycloakUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("KeycloakUserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakUserId");

                    b.HasIndex("KeycloakUserName");

                    b.ToTable("CollectActions");
                });

            modelBuilder.Entity("InterLoad.Models.Ef.CollectDemand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CollectableId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Demand")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("StockPeriodId")
                        .HasColumnType("integer");

                    b.Property<int>("SubProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("UltraOfficeSubProjectArticleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CollectableId");

                    b.HasIndex("StockPeriodId");

                    b.HasIndex("SubProjectId");

                    b.HasIndex("UltraOfficeSubProjectArticleId")
                        .IsUnique();

                    b.ToTable("CollectDemands");
                });

            modelBuilder.Entity("InterLoad.Models.Ef.CollectGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("MergeStockPeriods")
                        .HasColumnType("boolean");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("UltraOfficePackingSchemeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("CollectGroups");
                });

            modelBuilder.Entity("InterLoad.Models.Ef.CollectGroupEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupNr")
                        .HasColumnType("integer");

                    b.Property<int>("SubProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("UltraOfficePackingSchemeEntryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CollectGroupId");

                    b.HasIndex("SubProjectId");

                    b.ToTable("CollectGroupEntries");
                });

            modelBuilder.Entity("InterLoad.Models.Ef.Collectable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("UltraOfficeArticleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    b.HasIndex("UltraOfficeArticleId")
                        .IsUnique();

                    b.ToTable("Collectables");
                });

            modelBuilder.Entity("InterLoad.Models.Ef.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UltraOfficeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Reference");

                    b.HasIndex("UltraOfficeId")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("InterLoad.Models.Ef.StockPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UltraOfficeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("StockPeriods");
                });

            modelBuilder.Entity("InterLoad.Models.Ef.SubProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCollectable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("PrepSubProjectForId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("UltraOfficeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PrepSubProjectForId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UltraOfficeId")
                        .IsUnique();

                    b.ToTable("SubProjects");
                });

            modelBuilder.Entity("InterLoad.Models.Ef.UltraOfficeSyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HangfireJobId")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<long>("NextSyncId")
                        .HasColumnType("bigint");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("SyncDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UsedSyncId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UltraOfficeSyncLogs");
                });

            modelBuilder.Entity("CollectActionCollectDemand", b =>
                {
                    b.HasOne("InterLoad.Models.Ef.CollectAction", null)
                        .WithMany()
                        .HasForeignKey("CollectActionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterLoad.Models.Ef.CollectDemand", null)
                        .WithMany()
                        .HasForeignKey("CollectDemandsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterLoad.Models.Ef.CollectDemand", b =>
                {
                    b.HasOne("InterLoad.Models.Ef.Collectable", "Collectable")
                        .WithMany()
                        .HasForeignKey("CollectableId");

                    b.HasOne("InterLoad.Models.Ef.StockPeriod", "StockPeriod")
                        .WithMany()
                        .HasForeignKey("StockPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterLoad.Models.Ef.SubProject", "SubProject")
                        .WithMany()
                        .HasForeignKey("SubProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collectable");

                    b.Navigation("StockPeriod");

                    b.Navigation("SubProject");
                });

            modelBuilder.Entity("InterLoad.Models.Ef.CollectGroup", b =>
                {
                    b.HasOne("InterLoad.Models.Ef.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InterLoad.Models.Ef.CollectGroupEntry", b =>
                {
                    b.HasOne("InterLoad.Models.Ef.CollectGroup", "CollectGroup")
                        .WithMany()
                        .HasForeignKey("CollectGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterLoad.Models.Ef.SubProject", "SubProject")
                        .WithMany()
                        .HasForeignKey("SubProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectGroup");

                    b.Navigation("SubProject");
                });

            modelBuilder.Entity("InterLoad.Models.Ef.StockPeriod", b =>
                {
                    b.HasOne("InterLoad.Models.Ef.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InterLoad.Models.Ef.SubProject", b =>
                {
                    b.HasOne("InterLoad.Models.Ef.SubProject", "PrepSubProjectFor")
                        .WithMany()
                        .HasForeignKey("PrepSubProjectForId");

                    b.HasOne("InterLoad.Models.Ef.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrepSubProjectFor");

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
